### ISSUE TITLE
USART_CR1_M_Msk  define missing

### ISSUE THREAD

**Issue by UweBonnes** [STMicroelectronics/cmsis_device_h7rs#1]
Hello,

all other STM32 device headers define USART_CR1_M_Msk . for STM32H7RS it is missing. Please add.

**Comment by KRASTM** [comment]
ST Internal Reference: 182151

**Comment by KRASTM** [comment]
Hello @UweBonnes,

The issue you reported has been fixed in the frame of version v1.1.0 of the STM32CubeH7RS CMSIS published recently on GitHub. Thank you again for having reported.

With regards.
